### ISSUE TITLE
Erro java.lang.NullPointerException no modulo de impressão ao finalizar o pagamento 

### ISSUE THREAD

**Issue by mariolandossa** [jhonathanqz/stone_smart_flutter#26]
Bom dia, ao usar a aplicação de exemplo em uma pagamento a credito, finalizou com sucesso e ao imprimir o comprovante levantou essa  pilha de erro:

D/PrinterImpl( 4961): Print: start
D/PrinterManager( 4961): Status: 0
D/PrinterManager( 4961): Service: com.xcheng.printerservice.IPrinterService$Stub$Proxy@b47cce5
D/PrinterImpl( 4961): Print: Run execute
D/PrinterManager( 4961): Status: 0
D/PrinterManager( 4961): Service: com.xcheng.printerservice.IPrinterService$Stub$Proxy@b47cce5
D/PrinterManager( 4961): Status: 0
D/PrinterManager( 4961): Service: com.xcheng.printerservice.IPrinterService$Stub$Proxy@b47cce5
D/PrinterManager( 4961): hasPaper
D/PrinterImpl( 4961): Print: print
D/PrinterManager( 4961): print: start
D/PrinterManager( 4961): printBitmap: start
D/PrinterCallbackAdapter( 4961): onRealLength(current=30.0, total=35.0)(pending = 1)
E/ActivityThread( 4961): Failed to find provider info for br.com.positivo.stoneprovider.printerprovider
W/Binder  ( 4961): Binder call failed.
W/Binder  ( 4961): java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.content.ContentProviderClient.query(android.net.Uri, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String)' on a null object reference
W/Binder  ( 4961):      at br.com.stone.posandroid.hal.positivo.api.io.PrinterCallbackAdapter.onRealLength(PrinterCallbackAdapter.java:67)
W/Binder  ( 4961):      at com.xcheng.printerservice.IPrinterCallback$Stub.onTransact(IPrinterCallback.java:94)
W/Binder  ( 4961):      at android.os.Binder.execTransact(Binder.java:570)
W/System.err( 4961): java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.content.ContentProviderClient.query(android.net.Uri, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String)' on a null object reference
W/System.err( 4961):    at br.com.stone.posandroid.hal.positivo.api.io.PrinterCallbackAdapter.onRealLength(PrinterCallbackAdapter.java:67)
W/System.err( 4961):    at com.xcheng.printerservice.IPrinterCallback$Stub.onTransact(IPrinterCallback.java:94)
W/System.err( 4961):    at android.os.Binder.execTransact(Binder.java:570)
D/PrinterManager( 4961): printBitmap: end
D/PrinterManager( 4961): printStepWrapPaper: start
D/PrinterCallbackAdapter( 4961): onRealLength(current=10.0, total=46.63)(pending = 0)
E/ActivityThread( 4961): Failed to find provider info for br.com.positivo.stoneprovider.printerprovider
W/Binder  ( 4961): Binder call failed.
W/Binder  ( 4961): java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.content.ContentProviderClient.query(android.net.Uri, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String)' on a null object reference
W/Binder  ( 4961):      at br.com.stone.posandroid.hal.positivo.api.io.PrinterCallbackAdapter.onRealLength(PrinterCallbackAdapter.java:67)
W/Binder  ( 4961):      at com.xcheng.printerservice.IPrinterCallback$Stub.onTransact(IPrinterCallback.java:94)
W/Binder  ( 4961):      at android.os.Binder.execTransact(Binder.java:570)
W/System.err( 4961): java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursor android.content.ContentProviderClient.query(android.net.Uri, java.lang.String[], java.lang.String, java.lang.String[], java.lang.String)' on a null object reference
W/System.err( 4961):    at br.com.stone.posandroid.hal.positivo.api.io.PrinterCallbackAdapter.onRealLength(PrinterCallbackAdapter.java:67)
W/System.err( 4961):    at com.xcheng.printerservice.IPrinterCallback$Stub.onTransact(IPrinterCallback.java:94)
W/System.err( 4961):    at android.os.Binder.execTransact(Binder.java:570)
D/PrinterManager( 4961): printStepWrapPaper: end
D/PrinterManager( 4961): print: end
D/NativeCrypto( 4961): ssl=0x7ee74000 NativeCrypto_SSL_interrupt

**Comment by jhonathanqz** [comment]
Bom dia...
Conforme outro issue aberto, já entrei em contato com a Stone e falaram que o ambiente de Sandbox (testes), está INSTÁVEL e sem previsão para normalização!!!

**Comment by jhonathanqz** [comment]
@mariolandossa  Subi uma versão 1..0.11+2 para fins de correção sobre possível erro com o método de abort

**Comment by jhonathanqz** [comment]
@mariolandossa  Qual o progresso com o plugin? mesmos erros?

**Comment by mariolandossa** [comment]
Adicionei a classe controller conforme seu exeplo e fiz a inclusão do codigo do exemplo no meu App, conforme codigo abaixo:
`
// Automatic FlutterFlow imports
import '/backend/schema/structs/index.dart';
import '/backend/sqlite/sqlite_manager.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'index.dart'; // Imports other custom actions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!
import 'package:stone_smart_flutter/payments/utils/payment_types.dart';
import 'package:stone_smart_flutter/stone_smart_flutter.dart';
import '/payment/payment_controller.dart';

Future<String> pagStone(
  int venda,
  List<ItensVendaStruct> itens,
  String operacao,
  double? saldo,
) async {
  // Add your function code here!
    StoneSmart.instance().payment.activePinpad(appName: 'InfosigaCmd', stoneCode: '206192723');
    double total = 0;
    String total2 = "";
    int total3 = 0;
    double percent = saldo! * 0.1;
    print("percent ${percent.toString()}");
    percent = double.parse(percent.toStringAsFixed(2));
    print("percent2 ${percent.toString()}");
    total = double.parse((saldo + percent).toStringAsFixed(2));
    total2 = total.toString().replaceAll('.', '');
    total3 = int.parse(total2);
    print("Total: $total2");
    if(operacao == "CREDITO_AVISTA"){     
      StoneSmart.instance().payment.creditPayment(total3);   
    }else{
      StoneSmart.instance().payment.debitPayment(total3);   
    }                 
 
  return "";
}
`
Estou recebendo esse erro:
D/libc-netbsd(12069): getaddrinfo: dev2.infocast.com.br get result from proxy gai_error = 7
D/libc-netbsd(12069): getaddrinfo: dev2.infocast.com.br get result from proxy gai_error = 7
E/flutter (12069): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PAYMENT NEED INITIALIZE! 
E/flutter (12069):  TRY: StoneSmart._instance.initPayment(handler)
E/flutter (12069): #0      StoneSmart.payment (package:stone_smart_flutter/stone_smart_flutter.dart:35:7)
E/flutter (12069): #1      pagStone (package:infosiga_stone/custom_code/actions/pag_stone.dart:21:27)
E/flutter (12069): #2      _PagMesaWidgetState.build.<anonymous closure>.<anonymous closure> (package:infosiga_stone/pages/pag_mesa/pag_mesa_widget.dart:258:72)
E/flutter (12069): #3      _FFButtonWidgetState.build.<anonymous closure> (package:infosiga_stone/flutter_flow/flutter_flow_widgets.dart:116:42)
E/flutter (12069): #4      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1171:21)
E/flutter (12069): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
E/flutter (12069): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
E/flutter (12069): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
E/flutter (12069): #8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279:7)
E/flutter (12069): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167:27)
E/flutter (12069): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:499:20)
E/flutter (12069): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
E/flutter (12069): #12     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425:11)
E/flutter (12069): #13     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
E/flutter (12069): #14     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
E/flutter (12069): #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
E/flutter (12069): #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
E/flutter (12069): #17     _invoke1 (dart:ui/hooks.dart:328:13)
E/flutter (12069): #18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
E/flutter (12069): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
E/flutter (12069):

**Comment by jhonathanqz** [comment]
ai que está o Erro @mariolandossa , os métodos são como streams....

você precisa chamar inicialmente a funcao abaixo para iniciar a Stone:
StoneSmart.instance().payment.activePinpad(appName: 'InfosigaCmd', stoneCode: '206192723');


Ai la na classe que você fez o extends de IStoneHandler, no método `onFinishedResponse`, você vai receber o retorno quando ela terminar de ativar... se deu certo esse retorno, ai sim posteriormente você chama a funcao de pagamento que você preferir.... nesse exemplo que me mandou acima, ele está chamando as 2 ao mesmo tempo, por isso todos esses erros... Qualquer método que você chamar, a resposta SEMPRE vai vir na classe que você fez o extends de IStoneHandler

**Comment by mariolandossa** [comment]
Obrigado vou corrigir

**Comment by jhonathanqz** [comment]
Apenas complementando: @mariolandossa 

Todos os métodos da classe que você fez o extends de IStoneHandler, iram retornar um json como String, entao coloque para fazer o jsonDecode dessa resposta, e o objeto deve vir com as properties abaixo, podendo vir NULL.
O campo `method` se refere a acao que você chamou, exemplo: chamou funcao abortar, vai vir "abort", chamou funcao de transacao, vai vir "transaction", etc....

private int idFromBase;
  private String amount;
  private String cardHolderNumber;
  private String cardBrand;
  private String date;
  private String time;
  private String aid;
  private String arcq;
  private String transactionReference;
  private String saleAffiliationKey;
  private String entryMode;
  private String typeOfTransactionEnum;
  private String serialNumber;
  private String manufacture;
  private String actionCode;
  private int cardBrandId;

  private String method;
  private String transactionStatus;
  private String messageFromAuthorize;

  private String errorMessage;
  private String authorizationCode;
  private String transactionObject;

  private String userModel;
