### ISSUE TITLE
App modo release fecha ao tentar pagar em cartão 

### ISSUE THREAD

**Issue by mariolandossa** [jhonathanqz/stone_smart_flutter#40]
Após instalar a versão release e tentar executar o pagamento com cartão o app morre, só consegui pegar o log uma unica vez, recebi esse erro:
E/AndroidRuntime(20854): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(20854): Process: br.com.infocast.infosigacmd, PID: 20854
E/AndroidRuntime(20854): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(20854):        at android.os.AsyncTask$3.done(AsyncTask.java:325)
E/AndroidRuntime(20854):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
E/AndroidRuntime(20854):        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
E/AndroidRuntime(20854):        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(20854):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/AndroidRuntime(20854):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/AndroidRuntime(20854):        at java.lang.Thread.run(Thread.java:761)
E/AndroidRuntime(20854): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void br.com.stone.pay.core.PaymentProvider.cancelReadCard()' on a null object reference
E/AndroidRuntime(20854):        at br.com.stone.posandroid.providers.PosTransactionProvider.cancelAndStopPayment(SourceFile)
E/AndroidRuntime(20854):        at br.com.stone.posandroid.providers.PosTransactionProvider.abortPayment(SourceFile)
E/AndroidRuntime(20854):        at br.com.stone.posandroid.providers.PosTransactionProvider.abortPayment(SourceFile)
E/AndroidRuntime(20854):        at y5.c.i(SourceFile)
E/AndroidRuntime(20854):        at y5.c.s(SourceFile)
E/AndroidRuntime(20854):        at y5.c$a.onError(SourceFile)
E/AndroidRuntime(20854):        at stone.utils.RequestAsyncTaskAbstract.callStoneCallBackIfNeeded(SourceFile)
E/AndroidRuntime(20854):        at br.com.stone.posandroid.providers.PosTransactionProvider.callStoneCallBackIfNeeded(SourceFile)
E/AndroidRuntime(20854):        at br.com.stone.posandroid.providers.PosTransactionProvider.doInBackground(SourceFile)
E/AndroidRuntime(20854):        at android.os.AsyncTask$2.call(AsyncTask.java:305)
E/AndroidRuntime(20854):        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(20854):        ... 3 more
W/FlutterJNI(20854): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: stone_smart_flutter. Response ID: 39
W/FlutterJNI(20854): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: stone_smart_flutter. Response ID: 40

OBS: em modo debug funciona normalmente

**Comment by mariolandossa** [comment]
Favor desconsiderar o suporte da Stone informou que isso é um problema da assinatura da maquina de testes
